### ISSUE TITLE
Calling the sales_data method & returning None

### ISSUE THREAD

**Issue by viiszc** [wa1ker38552/rolimons.py#12]
Not sure if this is a bug or I'm doing something wrong.

**Comment by wa1ker38552** [comment]
I think Rolimon's changed their code for their sales data page which led to the data being unable to be scraped. I'll push out a fix by the end of the day 👍

**Comment by wa1ker38552** [comment]
Alright, added the fix. Should be in rolimons==1.51, let me know if you encounter further problems.

**Comment by viiszc** [comment]
Thanks a lot, appreciated man!
