### ISSUE TITLE
Are you able to get new limiteds list or inventory of a player?

### ISSUE THREAD

**Issue by ThunderFound** [wa1ker38552/rolimons.py#16]
Can find it. If i remember correctly, this was a thing in an older version

![image](https://github.com/wa1ker38552/rolimons.py/assets/90287659/c53712f1-61c5-43f2-bd98-c075da7ca800)
![image](https://github.com/wa1ker38552/rolimons.py/assets/90287659/1aef5963-8121-44eb-b387-bdef38fd6efe)

**Comment by wa1ker38552** [comment]
I think I removed fetching inventory because there was no Rolimons endpoint for it, previously, I did it using Roblox's API, I'm currently on vacation, but I'll try to add it back in once I'm back.

**Comment by ThunderFound** [comment]
I also found a bug or smth else. Maybe this bug is on rolimons' side.
When you are trying to get value of this item: https://www.roblox.com/catalog/**85754656**/Tyrannosaurus with .value func, it returns "Trex" value

![image](https://github.com/wa1ker38552/rolimons.py/assets/90287659/c642c4b5-0fa6-4f56-98d7-078dada169a4)

**Comment by wa1ker38552** [comment]
Oh I think I know why, its because in the Rolimon's API, it returns data as a list so if value isn't there everything gets shifted forward and the next one is probably acronym. I'll add a fix for this when I do the inventory scanning thing as well. I get back in 2 days.

**Comment by wa1ker38552** [comment]
I fixed the bug with value being replaced by acronym if it doesn't have an assigned value and added a new method under players called `fetch_inventory()` which returns a list of `rolimons.item` objects, hope this helps!👍
